name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *" # daily
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          user: manjunathh-xyz
          template: classic
          base: header, activity, community, repositories, metadata

          # ðŸ§  Languages
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_analysis_timeout: 15

          # ðŸ“Š Stats
          plugin_statistics: yes

          # ðŸ§© Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact

          # ðŸ”¥ Activity
          plugin_activity: yes
          plugin_activity_limit: 6
          plugin_activity_days: 14
          plugin_activity_filter: issue, pr, release, fork, review

          # ðŸ“¦ Repositories
          plugin_repositories: yes
          plugin_repositories_featured: |
            schemeforge
            repopulse
            kexra

          # ðŸŽ¨ Output
          filename: github-metrics.svg
